//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoeOverlayMvvm.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PoeOverlayMvvm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Name&quot;:&quot;Orb of Alteration&quot;,&quot;ShortName&quot;:&quot;alteration&quot;,&quot;Id&quot;:1,&quot;Value&quot;:0.087719298245614},{&quot;Name&quot;:&quot;Orb of Fusing&quot;,&quot;ShortName&quot;:&quot;fusing&quot;,&quot;Id&quot;:2,&quot;Value&quot;:0.3278688524590163},{&quot;Name&quot;:&quot;Orb of Alchemy&quot;,&quot;ShortName&quot;:&quot;alchemy&quot;,&quot;Id&quot;:3,&quot;Value&quot;:0.3389830508474576},{&quot;Name&quot;:&quot;Chaos Orb&quot;,&quot;ShortName&quot;:&quot;chaos&quot;,&quot;Id&quot;:4,&quot;Value&quot;:1},{&quot;Name&quot;:&quot;Gemcutter&apos;s Prism&quot;,&quot;ShortName&quot;:&quot;gcp&quot;,&quot;Id&quot;:5,&quot;Value&quot;:1},{&quot;Name&quot;:&quot;Exalted Orb&quot;,&quot;ShortName&quot;:&quot;exalted&quot;,&quot;Id&quot;:6,&quot;Value&quot;:94.5},{&quot;Name&quot;:&quot;Chromatic Orb&quot;,&quot;ShortName&quot;:&quot;chrome&quot;,&quot;Id&quot;:7,&quot;Value&quot;:0.1176470588235 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AllCurrencies {
            get {
                return ResourceManager.GetString("AllCurrencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&quot;alteration&quot;,&quot;chaos&quot;,&quot;exalted&quot;].
        /// </summary>
        internal static string PriceCurrencies {
            get {
                return ResourceManager.GetString("PriceCurrencies", resourceCulture);
            }
        }
    }
}
